### ISSUE TITLE
Invaild configuration about copilot extension

### ISSUE THREAD

**Issue by artwalker** [alfredodeza/rust-setup#1]
Hello, dear teacher,

I find in codespaces I have to install copilot extension, so I think there have some problems in your `devcontainer.json`.
So I think it needs some **modification**.
```json
	"customizations": {
		"vscode": {
			"extensions": [
				"rust-lang.rust-analyzer",
				"vadimcn.vscode-lldb",
                                "GitHub.copilot"
			]
		}
	}
```

And I pull a request for it and thank you for looking what I write.

Hope you have a good day!

**Comment by alfredodeza** [comment]
Thanks so much for catching that!
